name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Packing 
        run: dotnet pack SharedKernel/SharedKernel.csproj --configuration Release --output .

      - name: Pushing nuget package 
        run: dotnet nuget push  SharedKernel/bin/Release/NurRestaurantSharedKernel.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_REPO }}
