name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Adding github registry
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"

      - name: Packing 
        run: dotnet pack SharedKernel/SharedKernel.csproj --configuration Release

      - name: Pushing nuget package 
        run: dotnet nuget push  SharedKernel/bin/Release/SharedKernel.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "github"
